### ISSUE TITLE
female char headband artifact

### ISSUE THREAD

**Issue by themuntdregger** [UnoffLandz/unoff-landz#34]
All female chars seem to be created with a headband. Its not an issue with char creation but, some weirdness by the client. If the headband appears in the char sto then, it may be possible to remove it at the time the char is created. Hence, why this fix needs to be undertaken as part of the char sto milestone

**Comment by ChesterUL** [comment]
Does look cool to give female's headbands tho

**Comment by themuntdregger** [comment]
Hey Chester - good to hear from you again. I'm working on the headband issue so should have something soon
