### ISSUE TITLE
Database update error

### ISSUE THREAD

**Issue by themuntdregger** [UnoffLandz/unoff-landz#65]
When I run the U option, it creates the additional table in Game_data_table, but all the data is lost

**Comment by nemerle** [comment]
I think it should be working ok in the last commit: 842a2620e8be258e6c604d1f7468ff51a403bad1
If you can please verify

**Comment by themuntdregger** [comment]
Tried again. It creates the version table and adds the version number, but then terminates in a segfault.

**Comment by nemerle** [comment]
Hmm... can't recreate this. can you post the 'log' of the upgrade run ?
Mine looks like this:
```
UnoffLandz Server - version 4

DB version update 0 to 1:UPGRADE [v0]: Creating database backup - ver_0_of_unoff.db
UPGRADE [v1]: Success
OK
```

**Comment by themuntdregger** [comment]
Will do

**Comment by themuntdregger** [comment]
Now seems to work fine
