### ISSUE TITLE
e3d_conv and obj_conv

### ISSUE THREAD

**Issue by themuntdregger** [UnoffLandz/unoff-landz#66]
These are tools which are part of the UnoffLandz project and which convert Eternal Lands e3d models to Wavefront object (and vice versa). Currently the sourcecode is hosted on SourceForge:

https://sourceforge.net/projects/unoffserver/files/e3d%20converter/
https://sourceforge.net/projects/unoffserver/files/obj%20converter/

My proposal/idea is that we transfer source for the latest versions to Github and place it under tools sub-directory

**Comment by nemerle** [comment]
Agreed.
I've also started working in my copious free time on extending assimp to handle e3d models. If we manage to integrate assimp into client code we'll get a full support for loading other asset formats.

**Comment by themuntdregger** [comment]
Nice

Extending assimp to handle e3d seems like a pretty damn cool solution as it avoids the pain of having to convert files. 

It probably won't effect what you're doing with assimp but, (just in case it does), if you examine the data in many of EL's e3d models, you'll find up to 25% of entries in the index list are duplicates. My guess is the algorithm in EL's crappy blender macro's maybe somewhat less than optimal lol.

**Comment by themuntdregger** [comment]
Done
