### ISSUE TITLE
extern structs causing compile errors under C

### ISSUE THREAD

**Issue by themuntdregger** [UnoffLandz/unoff-landz#69]
eg :
struct attribute_ {
    int night_vision[MAX_PICKPOINTS];
    int day_vision[MAX_PICKPOINTS];
    int carry_capacity[MAX_PICKPOINTS];
};
extern struct attribute_ attribute[MAX_RACES];

Causes error under GCC.

**Comment by nemerle** [comment]
Hmm... that's strange I'm not seeing any errors on gcc 4.9 ?
What does it complain about ?

**Comment by themuntdregger** [comment]
I've also got 4.9 so sounds like something i'm doing wrong. However, for example, if I add extern to the client struct, I get:

||=== Build: server-debug in unoff-landz (compiler: GNU GCC Compiler) ===|
.objs/Server/main.o||In function `socket_accept_callback':|
main.c|| undefined reference to `clients'|
main.c|| undefined reference to `clients'|
main.c|| undefined reference to `clients'|
.objs/Server/main.o||In function `timeout_cb':|
main.c|| undefined reference to `clients'|
.objs/Server/main.o||In function `socket_read_callback':|
main.c|| undefined reference to `clients'|
.objs/Server/main.o:main.c|| more undefined references to `clients' follow|
||=== Build failed: 6 error(s), 0 warning(s) (0 minute(s), 3 second(s)) ===|

**Comment by nemerle** [comment]
Most likely you've not included all those .c files I've created, that are holding defined structs.
In this example clients struct is defined in clients.c

**Comment by themuntdregger** [comment]
Aha - sorted

thx nemerle
